### ISSUE TITLE
Spec necessary features

### ISSUE THREAD

**Issue by den1k** [den1k/vimsical-v1#98]
## Vims Config
1. Transpilers for HTML, CSS & JS
2. Dropdown of common JS libs to include
3. Option to link own scripts and stylesheets
4. Autorun JS

## Helpers 
5. Tidy code

## Editor UX
- [ ] double click on one editor header hides all other editors
- [ ] double click an editor if it is the only one shown header hides all other editors

## Default Editor Config (not visible to user)
- [ ] 2 space tab indentation

## Tasks
1. Transpilers
- [ ] editors can show compiled output (read-only)
- [ ] code-highlighting adapts to current transpiler
* HTML
  - [ ] Haml
* CSS
  - [ ] SCSS
  - [ ] LESS
  - [ ] Compass
* JS
  - [ ] babel

2. Dropdown Libs
* libs from https://cdnjs.com/
  * React
  * D3...

3. Option to link own styles and stylesheets
These get injected into `<head>`. 
- [ ] user can change load order

4. Autorun JS
- [ ] enabled by default

5. One click code tidying
